In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")
sns.set_palette("Set2")

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving ecommerce_customer_data_large.csv to ecommerce_customer_data_large (2).csv

In [ ]:
df = pd.read_csv("ecommerce_customer_data_large.csv")

In [ ]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female,0
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female,0
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female,0
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female,0
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female,0

In [ ]:
df.shape

(250000, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  object
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202618 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 24.8+ MB

In [ ]:
df.describe(include="all")

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
count,250000.000000,250000,250000,250000.000000,250000.000000,250000.000000,250000,250000.000000,202618.000000,250000,250000.000000,250000,250000.00000
unique,NaN,249728,4,NaN,NaN,NaN,3,NaN,NaN,39878,NaN,2,NaN
top,NaN,2021-11-30 18:52:48,Electronics,NaN,NaN,NaN,Credit Card,NaN,NaN,Michael Johnson,NaN,Male,NaN
freq,NaN,2,62630,NaN,NaN,NaN,83547,NaN,NaN,119,NaN,125676,NaN
mean,25017.632092,NaN,NaN,254.742724,3.004936,2725.385196,NaN,43.798276,0.500824,NaN,43.798276,NaN,0.20052
std,14412.515718,NaN,NaN,141.738104,1.414737,1442.576095,NaN,15.364915,0.500001,NaN,15.364915,NaN,0.40039
min,1.000000,NaN,NaN,10.000000,1.000000,100.000000,NaN,18.000000,0.000000,NaN,18.000000,NaN,0.00000
25%,12590.000000,NaN,NaN,132.000000,2.000000,1476.000000,NaN,30.000000,0.000000,NaN,30.000000,NaN,0.00000
50%,25011.000000,NaN,NaN,255.000000,3.000000,2725.000000,NaN,44.000000,1.000000,NaN,44.000000,NaN,0.00000
75%,37441.250000,NaN,NaN,377.000000,4.000000,3975.000000,NaN,57.000000,1.000000,NaN,57.000000,NaN,0.00000
max,50000.000000,NaN,NaN,500.000000,5.000000,5350.000000,NaN,70.000000,1.000000,NaN,70.000000,NaN,1.00000

In [ ]:
df.isnull().sum()

Customer ID                  0
Purchase Date                0
Product Category             0
Product Price                0
Quantity                     0
Total Purchase Amount        0
Payment Method               0
Customer Age                 0
Returns                  47382
Customer Name                0
Age                          0
Gender                       0
Churn                        0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df["Returns"] = df["Returns"].fillna(0)

df["Payment Method"] = df["Payment Method"].fillna(df["Payment Method"].mode()[0])

df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

In [ ]:
df["Purchase Date"] = pd.to_datetime(df["Purchase Date"])

In [ ]:
df.dtypes

Customer ID                int64
Purchase Date             object
Product Category          object
Product Price              int64
Quantity                   int64
Total Purchase Amount      int64
Payment Method            object
Customer Age               int64
Returns                  float64
Customer Name             object
Age                        int64
Gender                    object
Churn                      int64
dtype: object

In [ ]:
df.to_csv("cleaned_ecommerce_data.csv", index=False)